version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    #restart: always
  web:
    image: vaniltonpinheiro/api-nfe
    working_dir: /usr/src/app
    command: /bin/sh -c "./wait-for-it.sh db:5432 && python -u manage.py migrate && python -u manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    #restart: always
    depends_on:
      - db